services:
  db:
    image: mariadb:11.8
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:-root-password}
      MARIADB_USER: ${DATABASE_USER:-kotatsu}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD:-password}
      MARIADB_DATABASE: ${DATABASE_NAME:-kotatsu_db}
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ${DATABASE_DATA_PATH:-kotatsu-db}:/var/lib/mysql

  server:
    extends:
      service: server
      file: docker-compose.common.yaml
    depends_on:
      db:
        condition: service_healthy

volumes:
  kotatsu-db:
