services:
  server:
    container_name: kotatsu-sync
    build: .
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: ${DATABASE_USER:-kotatsu}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-password}
      DATABASE_NAME: ${DATABASE_NAME:-kotatsu_db}
      DATABASE_PORT: 3306
      JWT_SECRET: ${JWT_SECRET:-secret-string}
      ALLOW_NEW_REGISTER: ${ALLOW_NEW_REGISTER:-true}
