services:
  db:
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:-root-password}
      MYSQL_USER: ${DATABASE_USER:-kotatsu}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-password}
      MYSQL_DATABASE: ${DATABASE_NAME:-kotatsu_db}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ${DATABASE_DATA_PATH:-kotatsu-db}:/var/lib/mysql

  server:
    extends:
      service: server
      file: docker-compose.common.yaml
    environment:
      DATABASE_DIALECT: mysql
    depends_on:
      db:
        condition: service_healthy

volumes:
  kotatsu-db:
